### PR TITLE
Migrate php parser 2.0.0

### PR DESCRIPTION
**Pull request by ichiriac**

### CODE REVIEW

**Comment by chris-l** [comment]
Sorry! Been really busy this last 2 months with my day job.

But on this days I'll check everything on this PR, and then I'll accept it.

Thanks!

**Comment by ichiriac** [comment]
thanks @chris-l, I've tried to keep the code clean & jslinted

**Comment by krswanson** [comment]
Might this get merged soon?

**Comment by ichiriac** [comment]
Hi @chris-l,

Unfortunately you don't have time to maintain the lib (I understand as I also do it on my spare time), maybe you could give me access to merge and to publish to NPM.

I've started to use it also and the only way to deploy is by using the npm with my git repository. Please tell me if you are OK, or I'll open a new NPM repository in order to keep it updated.

Best Regards,
Ioan

**Comment by chris-l** [comment]
Hi! I just sent you an email about all this, please check it. 

I will merge this soon.

**Comment by chris-l** [comment]
Hi! Just want to let you know my progress: I'm currently checking how the unparser is working, and I'm fixing a few problems I have found.

My process is to parse some php code with php-parser, and then unparse the resulting AST with this new version of php-unparser. The desired result is that the code should pretty much stay the same, except for spaces and stuff like that.

And by doing that I found a few problems. For instance, this code `some::static()`, after doing that parsing->unparsing, was becoming `some::undefined()`. I already fixed that by changing line 9 on constref.js, so it passes the entire object to the `identifier` helper function, instead of only the name property.

Also, the `null` gets transformed to `[object Object]`, but I haven't found the reason yet. (null is a constant and therefore is also managed by constref.js, however the resulting code seems to be, -correctly- the string `"null"`, so I haven't found the reason yet. I will continue to check that one at night.)

`function a($a, $b) { }` gets converted to `function a(a, b) { }` (that is, it removes the $ symbol), I haven't checked that bug yet.

And after fixing those issues, I will continue my tests to see if there is anything else, and then I'll merge it.

Pretty much everything else seems to be working perfectly, so I hope is going to be done soon. ;-)

**Comment by ichiriac** [comment]
many thanks @chris-l 

The `$` was removed in v2 for every variable name, as the `$` is not a part of the name, so I've added it back on unparser (maybe forget one place)

In order to test syntax, you can use https://glayzzle.com/php-parser/

Here's an example of static call usage (and the reason why it does not works) :
PHP Script :
```php
<?php
some::thing();
$result = null;
```

AST Structure :
```json
{
  "kind": "program",
  "children": [
    {
      "kind": "call",
      "what": {
        "kind": "staticlookup",
        "what": {
          "kind": "identifier",
          "resolution": "uqn",
          "name": "some"
        },
        "offset": {
          "kind": "constref",
          "name": "thing"
        }
      },
      "arguments": []
    },
    {
      "kind": "assign",
      "operator": "=",
      "left": {
        "kind": "variable",
        "name": "result",
        "byref": false
      },
      "right": {
        "kind": "constref",
        "name": {
          "kind": "identifier",
          "resolution": "uqn",
          "name": "null"
        }
      }
    }
  ],
  "errors": []
}
```
You can also find the AST reference here : https://github.com/glayzzle/php-parser/blob/master/docs/AST.md#constref

**Comment by chris-l** [comment]
Well, sorry it took so looong!

I have tested with several php files, and it seems everything is working fine now, so I have just merged your changes.
Thanks a lot for the hard work and for your patience! ;)

**Pull request merged**
