### PR TITLE
comments and new nodes (php-parser 0.1.4)

### PR DESCRIPTION
**Pull request by ichiriac**
Various changes in order to fully scan and rebuild a project like magento 2 (for example)

- [x]  support compatibility with php-parser 0.1.4+
- [x]  add comments
- [x]  add interfaces
- [x]  fix constants

### CODE REVIEW

**Comment by ichiriac** [comment]
This one is ok for me, did not run jslint on it :smile: 

Next one will be travis & coveralls

**Comment by chris-l** [comment]
Ok, I separated and reordered the commits to several branches (according to what they do) and then merge them. Also fixed the jslint errors.

I didn't merge the magento part. (how that would work? only on travis - that is, not locally?)

This means I didn't merged your pull request manually and you need to update your local repo.

You can do it like this:

```
// I'm assuming you are both on master and on your latest commit, "fix short if" 361cf31
git checkout -b temporal
git checkout master
git fetch https://github.com/chris-l/php-unparser.git
git reset --hard FETCH_HEAD
git checkout temporal
git rebase master

// At this point, a conflict will arise. To fix it do this:
git checkout HEAD node_translators/index.js
git checkout HEAD node_translators/use.js
git rebase --continue

// an unnecessary commit will appear, just do this:
git rebase --skip

// The rebase is done
git checkout master
git merge --ff temporal
git branch -d temporal
```

After this, the no-yet-merged commits would be at the top of you `git log`

**Comment by ichiriac** [comment]
Thanks for the step-by-step help, but commits are still pending in this pull request, I can delete and re-fork the repository in order to avoid confusions.

**Comment by ichiriac** [comment]
The magento2 submodule is just for test driven dev purposes :

- in order to validate your local changes, you first `npm install` and `git submodule init` and next run `node test/index.js` - (or `npm run test`alias)
- when you commit changes (or receive a pull request) travis will also checkout and run same tests and warn you if something breaks
- when you publish with npm you can specify on ignore list the test path and anyway npm does not publish git submodules

---

You can also use a coverage tool like https://github.com/gotwarlost/istanbul that will report the code coverage, and also like for travis use a remote service for checking : https://coveralls.io/github/glayzzle/php-parser

> It would be better that you configure your own travis and coveralls accounts, so they will de facto linked with your repositories and automatically check any pull request

I've seen you are using JSLint, so you may be interested by https://codeclimate.com/, same as travis and coveralls, at each commit (or pull request) it will evaluate the code quality

**Pull request closed without merging**
