### PR TITLE
Dependencies update, more unparsing options, some fixes

### PR DESCRIPTION
**Pull request by b4dnewz**
Hi, **thanks** for the **great project**!

I've forked a while ago and worked on a little bit of changes, it work exactly the same but in one (important) function `helpers/body` it recive the context of the caller directly so it has already options and values in it and I've simplified the function and some random fixes in the structure.

I'm using this project (within php-writer) and I've decided to fork to try to improve it, also I've joined the **glayzzle** org/project to help them with the cause too.

I've also updated a little bit the readme file by adding options reference.

Let me know if I need to explain the changes made.
Thanks again.

### CODE REVIEW

**Comment by chris-l** [comment]
Thanks!

I'm checking your commits right now, I'll let you know as soon as possible.

**Comment by chris-l** [comment]
Ok, everything seems to be working fine, so I did the merge.

I also did some changes, like fixing some problems with jslint and changed the npm scripts so they execute the local version of browserify and uglify, and execute jslint along with the tests.

Thanks!

**Comment by b4dnewz** [comment]
@chris-l superb thanks for the reactivity!
btw this is a great module, great work!

**Comment by b4dnewz** [comment]
hi @chris-l can you bump the npm version and publish again?
I would like to point the [dependency of php-writer](https://github.com/glayzzle/php-writer/blob/master/package.json#L23) to your repository instead of my fork since now it has been merged.

Cheers.

**Pull request merged**
